version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: store-service-db
    environment:
      - MYSQL_ROOT_PASSWORD=milos1995
      - MYSQL_DATABASE=store-service-db
    ports:
      - "3306:3306"

  store-service:
    image: springapi
    container_name: store-service-springAPI
    build: .
    command: [ "java", "-jar", "app.jar", "--spring.liquibase.enabled=true" ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/store-service-db?useUnicode=true&characterEncoding=utf8&useSSL=false
    ports:
      - "8080:8080"